modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/DynamicTreesTeam/DynamicTrees-UpgradeAquatic/issues"

[[mods]]
modId="dtupgradeaquatic"
version="${file.jarVersion}"
displayName="Dynamic Trees for Upgrade Aquatic"

updateJSONURL="https://github.com/DynamicTreesTeam/DynamicTreesVersionInfo/blob/master/Add-ons/UpgradeAquatic.json?raw=true"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-upgrade-aquatic"

authors="Max Hyper"
description='''
Compatibility Mod between Dynamic trees and Upgrade Aquatic
'''
[[dependencies.dtupgradeaquatic]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.20,37)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtupgradeaquatic]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtupgradeaquatic]]
    modId="dynamictrees"
    mandatory=true
    versionRange="[0.10.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtupgradeaquatic]]
    modId="dynamictreesplus"
    mandatory=false
    versionRange="[0.1.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtupgradeaquatic]]
    modId="upgrade_aquatic"
    mandatory=true
    versionRange="[3.1.2,)"
    ordering="AFTER"
    side="BOTH"
